Repository 2021-fall-cs492c-team-10/monorepo, pull requests merged in 2021-11, with the labels that each got.

#15 Implement YouTube player
  packages/frontend/.eslintrc.json
  packages/frontend/package.json
  packages/frontend/src/App.css
  packages/frontend/src/App.test.tsx
  packages/frontend/src/App.tsx
  packages/frontend/src/components/Debug.tsx
  packages/frontend/src/components/YTPlayer.module.css
  packages/frontend/src/components/YTPlayer.test.tsx
  packages/frontend/src/components/YTPlayer.tsx
  packages/frontend/src/components/YTWrapper.module.css
  packages/frontend/src/components/YTWrapper.tsx
  packages/frontend/src/hooks/useScreenType.ts
  packages/frontend/src/hooks/useSize.ts
  packages/frontend/src/index.tsx
  packages/frontend/src/logo.svg
  packages/frontend/src/setupProxy.js
  packages/frontend/src/utils/debug.ts
  packages/frontend/src/utils/style.ts
  packages/frontend/src/utils/youtube.ts
  packages/frontend/tailwind.config.js
  yarn.lock
Labels: enhancement

#80 feat(voice): Implement Voice Chat
  .gitignore
  bin/generateSSL.js
  package.json
  packages/backend/src/entity/classroom.ts
  packages/backend/src/entity/history.ts
  packages/backend/src/entity/sso-account.ts
  packages/backend/src/entity/user.ts
  packages/backend/src/global.d.ts
  packages/backend/src/handlers/io.ts
  packages/backend/src/handlers/io/index.ts
  packages/backend/src/handlers/io/voice.ts
  packages/backend/src/passport.ts
  packages/backend/src/routes/auth/index.ts
  packages/backend/src/routes/auth/logout.ts
  packages/backend/src/routes/index.ts
  packages/backend/src/server.ts
  packages/backend/src/types/socket.ts
  packages/backend/src/utils/classroom.ts
  packages/backend/tsconfig.json
  packages/frontend/.eslintrc.json
  packages/frontend/package.json
  packages/frontend/src/App.tsx
  packages/frontend/src/components/Debug.tsx
  packages/frontend/src/components/Global.tsx
  packages/frontend/src/components/YTWrapper.test.tsx
  packages/frontend/src/components/YTWrapper.tsx
  packages/frontend/src/components/test/SocketStreamTest.tsx
  packages/frontend/src/hooks/useMediaRecorder.js
  packages/frontend/src/hooks/useSocket.ts
  packages/frontend/src/pages/Classroom.tsx
  packages/frontend/src/pages/Test.tsx
  packages/frontend/src/recoil/class/atom.ts
  packages/frontend/src/recoil/class/index.ts
  packages/frontend/src/recoil/class/videoId.ts
  packages/frontend/src/recoil/classroom/atom.ts
  packages/frontend/src/recoil/classroom/index.ts
  packages/frontend/src/recoil/classroom/videoId.ts
  packages/frontend/src/typing/@wmik/use-media-recorder.d.ts
  packages/frontend/src/typing/audio-recorder-polyfill/mpeg-encoder.d.ts
  packages/frontend/src/utils/VoiceBuffer.ts
  packages/frontend/src/utils/arrayBuffer.test.ts
  packages/frontend/src/utils/arrayBuffer.ts
  packages/frontend/tailwind.config.js
  packages/frontend/tsconfig.json
  packages/lib/package.json
  packages/lib/src/index.ts
  packages/lib/src/types/index.ts
  packages/lib/src/types/socket/common.ts
  packages/lib/src/types/socket/index.ts
  packages/lib/src/types/socket/voice.ts
  packages/lib/tsconfig.json
  proxy/certs/ssl.crt
  proxy/certs/ssl.key
  proxy/conf/nginx.conf.template
  yarn.lock
Labels: enhancement

#112 Toast: bug fix and add tests
  packages/frontend/src/components/ToastDisplay.test.tsx
  packages/frontend/src/components/ToastDisplay.tsx
Labels: automated-testing

#122 Implement class setting page
  packages/frontend/src/components/ClassSettingContent.tsx
  packages/frontend/src/components/test/ClassSettingPageTest.tsx
  packages/frontend/src/pages/Test.tsx
Labels: review-needed

#134 Implement Profilesetting page
  packages/frontend/src/components/ProfileSetting.tsx
  packages/frontend/src/components/SSOAccountList.tsx
  packages/frontend/src/components/UserProfile.tsx
  packages/frontend/src/components/test/SSOAccountListTest.tsx
  packages/frontend/src/utils/githubicon.png
  packages/frontend/src/utils/navericon.png
  packages/frontend/src/utils/profileicon.jpg
Labels: enhancement, review-needed

#159 feat(frontend): introduce cute loading screen and logo button
  packages/frontend/public/android-chrome-192x192.png
  packages/frontend/public/android-chrome-512x512.png
  packages/frontend/public/apple-touch-icon.png
  packages/frontend/public/browserconfig.xml
  packages/frontend/public/favicon-16x16.png
  packages/frontend/public/favicon-32x32.png
  packages/frontend/public/favicon.ico
  packages/frontend/public/index.html
  packages/frontend/public/logo192-alt.png
  packages/frontend/public/logo192.png
  packages/frontend/public/logo512-alt.png
  packages/frontend/public/logo512.png
  packages/frontend/public/safari-pinned-tab.svg
  packages/frontend/public/site.webmanifest
  packages/frontend/src/assets/logo-alt.svg
  packages/frontend/src/assets/logo.svg
  packages/frontend/src/components/buttons/LoginButton.module.css
  packages/frontend/src/components/buttons/LogoButton.module.css
  packages/frontend/src/components/buttons/LogoButton.tsx
  packages/frontend/src/components/layout/ContentPadding.tsx
  packages/frontend/src/components/layout/Debug.tsx
  packages/frontend/src/components/layout/Global.tsx
  packages/frontend/src/components/layout/Header.tsx
  packages/frontend/src/components/layout/Loading.module.css
  packages/frontend/src/components/layout/Loading.tsx
  packages/frontend/src/components/layout/LoadingLogo.tsx
Labels: review-needed

#188 feat(youtube): refactor codes and integrate into classroom components
  packages/backend/package.json
  packages/backend/src/io/YouTube.ts
  packages/backend/src/io/index.ts
  packages/backend/src/io/voice.ts
  packages/backend/src/managers/classroom.ts
  packages/backend/src/managers/user.ts
  packages/backend/src/passport.ts
  packages/backend/src/types/classroom.ts
  packages/frontend/src/components/layout/Global.tsx
  packages/frontend/src/components/test/SocketStreamTest.tsx
  packages/frontend/src/components/test/YouTubeSyncStudentTest.tsx
  packages/frontend/src/components/test/YouTubeSyncTest.tsx
  packages/frontend/src/components/voice/VoiceChat.tsx
  packages/frontend/src/components/youtube/YTSynchronizer.tsx
  packages/frontend/src/components/youtube/YTWrapper.module.css
  packages/frontend/src/hooks/useSocket.ts
  packages/frontend/src/pages/Classroom.tsx
  packages/lib/src/types/socket/YouTube.ts
  packages/lib/src/types/socket/voice.ts
Labels: review-needed
